spring:
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB

liquibase:
  enabled: false

app:
  image-folder: /home/denis/Denis/images
  tmp-folder: /home/denis/Denis/tmp
  image-extension: jpg