spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/painting_recognition
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#    hibernate.ddl-auto: create

liquibase:
  change-log: classpath:liquibase/master-changelog.xml

app:
  image-folder: /home/denis/Denis/images
  tmp-folder: /home/denis/Denis/tmp