spring:
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

liquibase:
  enabled: false

app:
  image-folder: /home/denis/Denis/images
  tmp-folder: /home/denis/Denis/tmp